# Generated by Django 3.2.9 on 2021-11-23 13:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_day'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('todoed', django.db.models.manager.Manager()),
            ],
        ),
    ]
