# Generated by Django 3.2.9 on 2021-11-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
            ],
        ),
    ]
